### PR TITLE
Round 2: New Charging Poles

### PR DESCRIPTION
**Pull request by undarl**
I've merged in your changes, and then my branch adding three new charging poles. Obviously if I'm going at something in an odd or inefficient way, please feel free to fix it or point it out to me. Once this is sorted out I still have the API/AAIPV branch to go.

The charging and draw power of the poles drops by halves from the original, which is now pole 4. I wrote migration files that seem to work properly -- they'll just need to be renamed once you set a new version number.

EDIT: I have not messed around with new graphics for any of the new poles. Not sure if that's something you'd want to do.

### CODE REVIEW

**Comment by undarl** [comment]
Not sure where you're at regarding this PR -- whether you've just been busy or whether it's taking more time and consideration.

If you'd prefer to put this off and try to get the API/AAIPV stuff in for a release, I can cancel and PR that instead. Let me know.

**Comment by avosirenfal** [comment]
I've just been busy, I'll take a look at it this weekend :)

Sorry for the wait

**Comment by undarl** [comment]
No worries. :)

**Comment by avosirenfal** [comment]
Please reformat control.lua to use tabs instead of spaces so I can look at a proper diff on GitHub. Your editor appears to have replaced all my indentation :P

Thanks.

**Comment by undarl** [comment]
Well, that was an adventure. There were two problems happening here at once.

Problem 1 was, indeed, some indentation weirdness. That was an easy fix.

Problem 2 is a line-ending mismatch. The copy of control.lua in your repo appears to be using Windows-style CRLF line endings. A local diff between my edited file and yours (downloaded from the repo) has the same problem as GitHub, but if I run unix2dos on mine or dos2unix on yours the problem goes away.

I can fix it locally, but my git is flatly refusing to upload CRLF-formatted files. That may be a config setting -- my git-fu is still weaker than I'd like.

I will continue to poke around for a solution, and will happily take suggestions.

**Comment by avosirenfal** [comment]
Take a look here: https://help.github.com/articles/dealing-with-line-endings/

**Comment by undarl** [comment]
Well, that all was a learning experience. Sorry, and I appreciate your patience.

After much burning and salting of the earth, we have a clean diff.

**Comment by avosirenfal** [comment]
Looks good to me. Sorry for the annoyance but this needed to be sorted out before the big PR because that one presumably has quite a few changes to control.lua.

I'm not going to test this because nothing jumps out at me as a problem and I'm assuming you've done due diligence :P

**Comment by undarl** [comment]
Yup, fair.

I'll get the final one going ASAP. Going to move very carefully after this whole ordeal. :)

**Pull request merged**
