### PR TITLE
Updated for 0.15

### PR DESCRIPTION
**Pull request by Ranakastrasz**
Also moved localizations into correct folder. Not sure if factorio
changed how it handles them or what, but it was all missing keys.

### CODE REVIEW

**Comment by avosirenfal** [comment]
Thanks! I'll upload this to the mod portal in a little bit.

**Comment by Ranakastrasz** [comment]
Awesome. Glad to help.

Its just that this is one of the mods I really need to play the game, and couldn't let it be delayed, XD.

**Comment by avosirenfal** [comment]
I'm just really happy some people actually like it and use it :)

It didn't get many downloads on the mod portal, probably because of my terrible description

**Comment by Ranakastrasz** [comment]
Hmm, maybe. I just wanted a replacement for... My mod, modular armor, which I just can't get to handle power network charging anymore since vehicles with modular armor got added. Hence Looking for a new mod. While I suspect I was the first to make a mod with this kind of functionality, I am glad to see other people are doing the same thing, and far better.

Main thing I might "Complain" about is that the multiple tiers seems uneeded, or at least no need for 4 of them. At best, I would say, one for Red circuit tech, and then one for Blue circuit and modules tech, which has less power waste, more range, and so on. A basic one and an End game one. give them different techs and so on.

As it is, you research it, and go right ahead and build the T4 version, no reason for anything less.

**Comment by undarl** [comment]
> Main thing I might "Complain" about is that the multiple tiers seems uneeded, or at least no need for 4 of them. At best, I would say, one for Red circuit tech, and then one for Blue circuit and modules tech, which has less power waste, more range, and so on. A basic one and an End game one. give them different techs and so on.
>
>As it is, you research it, and go right ahead and build the T4 version, no reason for anything less.

You seem to be looking at a different problem-solution set than I was when I contributed the additional poles. I didn't intend for the levels of pole to be "worst to best". The original one was the highest-power one, the 40MW draw. However, I often enjoy building smaller bases or outposts with self-contained power, and a 40MW draw can flatline a smaller base. Thus, lower-draw poles to suit lower power availability.

That said, I see your point as well. Additional technologies that could increase the transfer efficiency don't seem out of line.

**Pull request merged**
